### ISSUE TITLE
language translation

### ISSUE THREAD

**Issue by janwyczawski** [MaciPaci/Simulation-of-Underactuated-AUV-Control-Algorithms#1]
Hi,
I would really like to use your repo, but unfortunately I can't understand polish. Pls add english translation : ^ )
(uwu)

**Comment by MaciPaci** [comment]
Hi Jan. Unfortunately this repo is no longer actively maintained and serves educational purpose. Hope this helps :)

**Comment by janwyczawski** [comment]
oki doki
